- name: DDVE Login, Get X-DD-AUTH-TOKEN, Change Password, Set Passphrase
  hosts: localhost
  gather_facts: no
  connection: local

  vars_files:
    - /home/bhaven/terraform/ansible/gcp_tf_ansible_vars_file.yaml
  vars:
##    DDVE_IP: 34.87.116.17
    DDVE_IP: "{{ tf_ddve_ip }}"
##    default_password: '7280780451174975459'
    default_password: "{{ tf_ddve_instance_id }}"
    URI_1: https://{{ DDVE_IP }}:3009/rest/v1.0
    URI_2: https://{{ DDVE_IP }}:3009/rest/v2.0
    user: sysadmin
    new_Password: Password123!
    access_token: "{{ rest_post.x_dd_auth_token }}"
    new_passphrase: Password123!

  tasks:
  - name: Wait until {{ DDVE_IP }}/api/doc is comming online
    uri:
      validate_certs: false
      url: https://{{ DDVE_IP }}/api/doc
      status_code: 200
      method: GET
    register: _result
    until: _result.status == 200
    retries: 720 # 720 * 5 seconds = 1hour (60*60/5)
    delay: 5 # Every 5 seconds

  - name: Authenticate to API and retrieve authentication token
    uri:
      validate_certs: false
      status_code: 201
      url: "{{ URI_1 }}/auth"
      method: POST
      body:
        username: "{{ user }}"
        password: "{{ default_password }}"
      headers:
        Content-Type: application/json
      body_format: json
      return_content: true
    register: rest_post

  - name: DEBUG / GOT INFO
    debug:
      msg: "{{ rest_post.x_dd_auth_token }}"
    when: rest_post.status ==  201

  - name: change from default login with new password
    uri:
      validate_certs: false
      status_code: 200
      url: "{{ URI_1 }}/dd-systems/0/users/sysadmin"
      method: PUT
      body_format: json
      body:
        new_password: "{{ new_Password }}"
        current_password: "{{ default_password }}"
      headers:
          X-DD-AUTH-TOKEN: "{{ access_token }}"
          Content-Type: 'application/json'
      return_content: true
    register: rest_response

  - name: DEBUG DD default password change / GOT INFO
    debug:
      msg: "{{ rest_response }}"
    when: rest_response.status ==  200
